#!/usr/bin/env bash

# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

# Store this file as .git/hooks/commit-msg in your repository in order to
# enforce checking for proper commit message format before actual commits. You
# may need to make the script executable by 'chmod +x .git/hooks/commit-msg'.

# commit-msg use go-gitlint tool, install go-gitlint via `go get github.com/llorllale/go-gitlint/cmd/go-gitlint`
if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]
then
    ./tool/gitlint --path="./.git" --msg-file="$1"
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]
then
    ./tool/gitlint.exe --path="./.git" --msg-file="$1"
fi