@startuml sequence-diagram
'https: //plantuml.com/sequence-diagram

Actor -> MessageController: 1.1 获取消息列表
MessageController -> MessageService: 1.2 查询消息列表
MessageService -> UserService: 1.3 获取发送者信息
MessageService <-- UserService: 1.4 返回数据
MessageService -> RedisUtil: 1.5 获取缓存信息
MessageService <-- RedisUtil: 1.6 返回数据
MessageController <-- MessageService: 1.7 返回封装合并好的消息数据
Actor <-- MessageController: 1.8 返回消息列表
VlogService --> MessageService: 2.1 发送者点赞视频
MessageController <-- MessageService: 2.2 发送点赞视频信息
Actor <-- MessageController: 2.3 返回点赞信息
CommentService --> MessageService: 3.1 发送者评论
MessageController <-- MessageService: 3.2 发送评论信息
Actor <-- MessageController: 3.3 返回评论信息
CommentService --> MessageService: 4.1 发送者点赞评论
MessageController <-- MessageService: 4.2 发送点赞评论信息
Actor <-- MessageController: 4.3 返回点赞评论信息
FansService --> MessageService: 5.1 发送者关注接收者
MessageService -> RedisUtil: 5.2 获取用户关系
MessageService <-- RedisUtil: 5.3 返回缓存数据
MessageController <-- MessageService: 5.4 发送被关注信息
Actor <-- MessageController: 5.5 返回关注信息

@enduml