@startuml sequence-diagram
'https: //plantuml.com/sequence-diagram


Actor -> UserController: 1.1 查询用户信息
Actor -> UserController: 2.1 更改用户信息
Actor -> UserController: 3.1 修改头像或背景图
UserController -> RedisCacheUtil: 1.2 获取对象信息
RedisCacheUtil --> UserController: 1.2.1 返回
UserController --> Actor: 1.2.2 返回用户信息
UserController -> UserService: 1.3 获取查询的用户对象信息
UserService --> RedisCacheUtil: 1.4 设置对象信息
RedisCacheUtil --> UserController: 1.5 返回
UserController --> Actor: 1.6 返回用户信息
UserController -> UserInfoModifyType: 2.2 校验修改信息是否正确
UserInfoModifyType -> UserInfoModifyType: 2.3 重新检查
UserInfoModifyType -> UserService: 2.4 提交用户更新类型信息
UserService --> RedisCacheUtil: 2.5 设置对象信息
RedisCacheUtil --> UserController: 2.6 返回
UserController --> Actor: 2.7 返回更改状态
UserController -> MinioService: 3.2 上传图片
MinioService -> UserService: 3.3 提交用户更改的信息
UserService --> RedisCacheUtil: 3.4 设置对象信息
RedisCacheUtil --> UserController: 3.5 返回
UserController --> Actor: 3.6 返回更改结果
@enduml