@startuml sequence-diagram
'https: //plantuml.com/sequence-diagram

autonumber

客户端 -> 认证服务器: 输入手机号，获取验证码操作
认证服务器 -> 短信服务器: 请求短信验证码
短信服务器 --> 认证服务器: 发送短信验证码
认证服务器 --> 客户端: 返回短信验证码
客户端 -> 认证服务器: 填写验证码，执行登录操作
认证服务器 -> 认证服务器: 验证当前账号token和reflashToken是否可用
认证服务器 --> 客户端: 返回状态和token
客户端 -> 认证服务器: 登录后请求接口
认证服务器 -> 认证服务器: 验证当前账号token和以及token是否过期
认证服务器 --> 客户端: 返回状态
@enduml