@startuml sequence-diagram
'https: //plantuml.com/sequence-diagram



Actor -> CommentController: 1.1 发布评论内容
Actor -> CommentController: 2.1 获取评论数量
Actor -> CommentController: 3.1 获取评论列表
Actor -> CommentController: 4.1 删除评论
Actor -> CommentController: 5.1 点赞评论
Actor -> CommentController: 6.1 取消点赞评论
CommentController -> UserService: 1.2 校验评论对象
CommentController <-- UserService: 1.3.1.1 失败
CommentController --> Actor: 1.3.1.2 返回错误信息
UserService -> CommentService: 1.3.2 提交评论并保存
CommentService -> VlogService: 1.4 评论数量达到阈值，数据入库
CommentService -> RedisUtil: 1.5 评论数+1
CommentController <-- CommentService: 1.6 返回
CommentController --> Actor: 1.7 返回最新评论列表
CommentController -> RedisUtil: 2.2 缓存读取
CommentController <-- RedisUtil: 2.3 返回
CommentController --> Actor: 2.4 返回评论数量
CommentController -> CommentService: 3.2 获取评论列表
CommentService --> CommentController: 3.3 返回
CommentController --> Actor: 3.4 返回评论列表
CommentController -> CommentService: 4.2 删除选中评论
CommentService -> RedisUtil: 4.3 评论数-1
CommentService --> CommentController: 4.4 返回
CommentController --> Actor: 4.5 返回删除是否成功信息
CommentController -> RedisUtil: 5.2 点赞数+1
CommentController -> MessageService: 5.3 点赞通知
CommentController --> Actor: 5.4 返回点赞信息
CommentController -> RedisUtil: 6.2 点赞数-1
CommentController --> Actor: 6.3 返回取消点赞信息
@enduml